name: aplikasi_kasir
description: "Aplikasi kasir Point of Sale (POS) profesional."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
 
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
 
  intl: ^0.19.0 
  uuid: ^4.4.0 # <-- PERBAIKAN: Package ini ditambahkan kembali
  pdf: ^3.10.8
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true